### ISSUE TITLE
"Edit this page" button takes to a wrong URL

### ISSUE THREAD

**Issue by ashraymehta** [devopsfaith/krakend-documentation#126]
The "Edit this page" button from the KrakenD documentation website takes to a wrong URL. The URL appears to expect the documentation in a `docs/` folder in the repository.

#### Steps to reproduce:
* Visit a documentation page like https://www.krakend.io/docs/overview/introduction/
* Click on "Edit this page"
* Observe the resulting URL is https://github.com/devopsfaith/krakend-documentation/edit/master/docs/overview/introduction.md
* Expected URL: https://github.com/devopsfaith/krakend-documentation/edit/master/overview/introduction.md

**Comment by ashraymehta** [comment]
I assume that the issue is with a Hugo configuration and can't be fixed by a PR to this repository. If not, please let me know how. :)

**Comment by obokaman-com** [comment]
Thanks for reporting @ashraymehta. You're right, it was an error in the Hugo template referencing to the documentation. 

Just fixed it and republished the docs. Could you please verify, so we can close the issue?

**Comment by ashraymehta** [comment]
@obokaman-com Looks good now. Thanks!

**Comment by ashraymehta** [comment]
On a related note, would it be possible to keep the Hugo configuration in the repository itself and publish the website using a GitHub action? That'll mean people like me could potentially fix the issue themselves by raising a PR. Also, it might mean lesser manual work for you. :)

**Comment by alombarte** [comment]
Hello @ ashraymehta, there is a fully automated pipeline to publish our website. The documentation is only a fraction of what there is in our Hugo, which is kept as a private repository. The documentation contents can be edited and submit a PR, and once we validate it goes live automatically. Unfortunately what you found is part of the layout that lives in the private repo. We could add a sample Hugo configuration to play locally with the documentation, but it would be a different Hugo than the one we have in the private repo.

Thanks for your contribution!

**Comment by ashraymehta** [comment]
Thanks for the explanation @alombarte!
