### ISSUE TITLE
Document missing options

### ISSUE THREAD

**Issue by alombarte** [devopsfaith/krakend-documentation#147]
Some of the following options are not in the docs:
https://github.com/luraproject/lura/blob/4d35e4812fc689fbac8009fa3fe85371d6f56c52/config/parser.go#L140-L154

**Comment by kpacha** [comment]
here you have the list with comments: https://github.com/luraproject/lura/blob/4d35e4812fc689fbac8009fa3fe85371d6f56c52/config/config.go#L57-L139

**Comment by alombarte** [comment]
Pushed to v2.0 branch
