### ISSUE TITLE
Add documentation for static proxy

### ISSUE THREAD

**Issue by kpacha** [devopsfaith/krakend-documentation#19]
The static proxy is not documented.

- It injects static data into the response before returning it to the router.
- It supports different strategies for deciding if the static data should be added or not

Here, an example from the integration tests: https://github.com/devopsfaith/krakend/blob/master/test/krakend.json#L9-L30

supported strategies:
- always
- success
- errored
- complete
- incomplete

what do they mean? https://github.com/devopsfaith/krakend/blob/master/proxy/static.go#L100-L104

**Comment by alombarte** [comment]
See GH-24
