### ISSUE TITLE
Logging, metrics and tracers

### ISSUE THREAD

**Issue by alombarte** [devopsfaith/krakend-documentation#34]
- Types of metrics you can see (timers, gauges, histograms… of your requests)
- Metrics (/__stats endpoint)
- Using the metrics
~- Sending metrics to Influx~
- Logger (logrus, logstash)
~- Opencensus Exporters~
~- Send traces to InfluxDB~
~- Send traces to Zipkin~
~- Send traces to Prometheus~
~- Send traces to Jaeger~
~- Send traces to Logger~

**Comment by rgomezcasas** [comment]
If someone wants to export metrics in KrakenD using Prometheus needs to add to the `extra_config`:
```json
    "github_com/devopsfaith/krakend-opencensus": {
      "exporters": {
        "prometheus": {
          "port": 9100
        }
      }
    }
```

**Comment by kpacha** [comment]
here you'll find an example of several exporters: https://github.com/devopsfaith/krakend-opencensus/blob/master/example/krakend.json#L33-L68

**Comment by alombarte** [comment]
https://www.krakend.io/docs/extended-metrics/metrics/
