### ISSUE TITLE
Document flatmap filtering

### ISSUE THREAD

**Issue by kpacha** [devopsfaith/krakend-documentation#37]
Supported operations:

- Delete by matching pattern
- Move from src pattern to dst pattern

Pattern rules:

- Keys are separated by `.`
- `*` is a wildcard and matches any kind of key (property name or collection element)

Sample backend definition with flatmap filter:

```
 {
    "host": [ "http://127.0.0.1:8081" ],
    "url_pattern": "/collection/{id}",
    "is_collection": true,
    "extra_config": {
        "github.com/devopsfaith/krakend/proxy": {
            "flatmap_filter": [
                {
                    "type": "move",
                    "args": ["collection", "paths"]
                },
                {
                    "type": "del",
                    "args": ["paths.*.i"]
                },
                {
                    "type": "move",
                    "args": ["paths.*.path", "paths.*.url"]
                }
            ]
        }
    }
}
```

notice: when the flatmap filter is enabled, the `withelist`, `blacklist` and `mapping` attributes are ignored (`group` and `target` are still in use).

Move patterns (src => dst):

| src | dst | allowed |
| --- | --- | --- |
| `"a.*.b.*.c"` | `"a.*.b.*.d"` | 👍 |
| `"a.*.b.*.c"` | `"a.*.c"` | 👎 |
| `"a.b.c"` | `"c"` | 👍 |
| `"a.*.b.c"` | `"c"` | 👎 |
| `"a.*.b.c"` | `"a.*.b.*.d.*.e"` | 👎 |
| `"a.*.b.*.c"` | `"a.*.b.*.c.d.e.f.g"`|  👍|
| `"a.*.b.*.c"` | `"a.*.x.*.c.d.e.f.g"` | 👎 |
| `"a.*.b.*.c"` | `"a.*.x.*.c"` | 👎 |

**Comment by alombarte** [comment]
https://www.krakend.io/docs/backends/flatmap/
