### ISSUE TITLE
BloomFilter Guide

### ISSUE THREAD

**Issue by TerraSkye** [devopsfaith/krakend-documentation#41]
Hello i've been wanting to configure the `bloomfilter` plugin 
therefore ive been looking for documentation and could not find much information about how to set it up within krakenD, it would be great if you can make a how to guide on how to setup the bloomfilter

something like how to configure the the bloomfilter in the config, as well as to have an example of sending a token which then gets declined by the gateway.

**Comment by kpacha** [comment]
A working example: https://github.com/devopsfaith/krakend-playground/pull/8

you can try to revoke the custom token `mnb23vcsrt756yuiomnbvcx98ertyuiop` (https://github.com/devopsfaith/krakend-playground/blob/master/data/token.json#L6) and you'll go from here

```
$ curl -iH'Authorization: bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InNpbTIifQ.eyJhdWQiOiJodHRwOi8vYXBpLmV4YW1wbGUuY29tIiwiZXhwIjoxNzM1Njg5NjAwLCJpc3MiOiJodHRwczovL2tyYWtlbmQuaW8iLCJqdGkiOiJtbmIyM3Zjc3J0NzU2eXVpb21uYnZjeDk4ZXJ0eXVpb3AiLCJyb2xlcyI6WyJyb2xlX2EiLCJyb2xlX2IiXSwic3ViIjoiMTIzNDU2Nzg5MHF3ZXJ0eXVpbyJ9.htgbhantGcv6zrN1i43Rl58q1sokh3lzuFgzfenI0Rk' http:/192.168.99.100:8080/private/custom
HTTP/1.1 200 OK
Cache-Control: public, max-age=300
Content-Type: application/json; charset=utf-8
X-Krakend: Version 0.9.0
X-Krakend-Completed: true
Date: Wed, 15 May 2019 14:07:10 GMT
Content-Length: 251

{"address":{"city":"New York","postalCode":"10021","state":"NY","streetAddress":"21 2nd Street"},"age":25,"firstName":"John","id_user":1,"lastName":"Smith","phoneNumber":[{"number":"212 555-1234","type":"home"},{"number":"646 555-4567","type":"fax"}]}%  
```
to here
```
$ curl -iH'Authorization: bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InNpbTIifQ.eyJhdWQiOiJodHRwOi8vYXBpLmV4YW1wbGUuY29tIiwiZXhwIjoxNzM1Njg5NjAwLCJpc3MiOiJodHRwczovL2tyYWtlbmQuaW8iLCJqdGkiOiJtbmIyM3Zjc3J0NzU2eXVpb21uYnZjeDk4ZXJ0eXVpb3AiLCJyb2xlcyI6WyJyb2xlX2EiLCJyb2xlX2IiXSwic3ViIjoiMTIzNDU2Nzg5MHF3ZXJ0eXVpbyJ9.htgbhantGcv6zrN1i43Rl58q1sokh3lzuFgzfenI0Rk' http:/192.168.99.100:8080/private/custom
HTTP/1.1 401 Unauthorized
Date: Wed, 15 May 2019 14:07:41 GMT
Content-Length: 0

```

**Comment by alombarte** [comment]
From our Slach channel (@kpacha):
```
I've just pushed a PR to the playground with another example for the BF remote client. https://github.com/devopsfaith/krakend-playground/pull/8

Notice it's intended to manage just one remote instance. a more realistic example should include a set of clients and some integration with your service discovery system in order to keep that set updated

another thing that example doesn't show is the use of the method `Union`, intended to update the remote set with its merge with the local one. It's very useful for massive updates and synchronization between instances
```

**Comment by softzilla** [comment]
In addition to bloomfilter configuration parameters, documentation should explain how bloofilter works in general:
- Explain that revocation logic implemented somewhere outside krakend. Link to example: (https://github.com/devopsfaith/krakend-playground/tree/master/jwt-revoker)
- Explain that interaction with bloomfilter done with help of bloomfilter Clinet over RPC (there no HTTP endpoints) (https://github.com/devopsfaith/bloomfilter/blob/master/rpc/client/client.go)

**Comment by alombarte** [comment]
The Bloom filter documentation has been extended on #27 and several other commits.

It might not be perfect but it goes through the topics claimed here: https://www.krakend.io/docs/authorization/revoking-tokens/

I am closing this task, but feel free to create an issue for any specific topic it still needs explanation.

Thanks!
