### ISSUE TITLE
Plain HTTP download

### ISSUE THREAD

**Issue by benatkin** [devopsfaith/krakend-documentation#91]
On https://www.krakend.io/download/ the download (Download tgz) is served with plain http. Additionally:

- manually changing the url to https doesn't work
- the GitHub releases doesn't contain binaries
- the SHA is served with plain HTTP

There are other options but it is nice that with go I can download binaries, but without https this option seems unwieldy.

**Comment by alombarte** [comment]
Thank you for your comment @benatkin, this will be under consideration.

**Comment by alombarte** [comment]
Thanks @benatkin, we have enabled https in our open source repository as well. You can manually change the URL until the changes are reflected in the website.
